version: '2'
services:

    # Uncomment this if you need to test the tracing system locally
    # Also set APP_ENV to production.
    #  jaeger:
    # tutorial   image: jaegertracing/all-in-one:latest
    #    ports:
    #      - 16686:16686

    php:
        image: digitalidea/laravel
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - mongodb
            - beanstalkd
            - mail
        ports:
            - 80:80
            - 8080:8080
        environment:
            - XDEBUG_ENABLED=true
            - VIRTUAL_HOST=universe.localhost
            - VIRTUAL_PORT=80
        networks:
             - mysql-compose-network
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "mysql"
            MYSQL_DATABASE: "mysql"
        ports:
            - "3306:3306"
        volumes:
            -  ~/.universe/mysql/data:/var/lib/mysql
        networks:
            - mysql-compose-network

networks:
    mysql-compose-network:
        driver: bridge


